FROM openjdk:11
EXPOSE 8089
ADD target/employee-management-system.0.0.1-SNAPSHOT.jar.original employee-management-system.0.0.1-SNAPSHOT.jar.original
ENTRYPOINT [ "java","/employee-management-system.0.0.1-SNAPSHOT.jar.original"]